[build]
  publish = "frontend/static"
  command = "echo 'Static deployment - no build needed'"

# No Python dependencies needed for static deployment
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
